name: Test Pull Requests

on:
  pull_request:

jobs:
  test:
    name: Test Pull Requests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build

      - name: Build distributions
        run: python -m build --sdist --wheel --outdir dist/

      - name: Test build
        run: |
          python -m pip install dist/*.whl
          # Optional: Add commands to test the package functionality
