name: Test Pull Requests

on:
  pull_request:
permissions:
  contents: read
  
jobs:
  test:
    name: Test Pull Requests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build

      - name: Build distributions
        run: python -m build --sdist --wheel --outdir dist/

      - name: Test build
        run: |
          python -m pip install dist/*.whl
          # Optional: Add commands to test the package functionality
